export const navItems = [
  { id: 'dashboard', label: 'Dashboard', shortLabel: 'Home', icon: 'dashboard' },
  { id: 'planner', label: '4-Year Planner', shortLabel: 'Planner', icon: 'planner' },
  { id: 'checklist', label: 'Degree Checklist', shortLabel: 'Checklist', icon: 'checklist' },
  { id: 'flowchart', label: 'Economics Prep Flowchart', shortLabel: 'Flowchart', icon: 'flowchart' },
  { id: 'resources', label: 'Resource Hub', shortLabel: 'Resources', icon: 'resources' },
  { id: 'chat', label: 'Campus Q&A', shortLabel: 'Q&A', icon: 'chat' },
  { id: 'dates', label: 'Dates & Links', shortLabel: 'Dates', icon: 'calendar' },
]

export const studentProfile = {
  name: 'Maya Hernandez',
  firstName: 'Maya',
  initials: 'MH',
  major: 'B.A. Economics',
  college: 'College of Letters & Science',
  year: 'Second Year',
  completedPercent: 68,
  unitsCompleted: 112,
  expectedGraduation: 'Spring 2028',
  standing: 'Good standing',
}

export const dashboardMetrics = [
  { label: 'Completed units', value: '112 / 180', tone: 'sky' },
  { label: 'Current GPA', value: '3.72', tone: 'silver' },
  { label: 'Planned next quarter units', value: '14', tone: 'emerald' },
  { label: 'Registration hold status', value: 'No holds', tone: 'indigo' },
]

export const dashboardDestinations = [
  {
    viewId: 'planner',
    title: '4-Year Planner',
    description: 'Map major, GE, and elective courses across all four years and balance unit load each quarter.',
    icon: 'planner',
    accent: 'from-sky-500/22 to-sky-500/0',
    tags: ['Roadmap', 'Quarters', 'Units'],
  },
  {
    viewId: 'checklist',
    title: 'Degree Checklist',
    description: 'See which GE areas, major requirements, and electives are complete, planned, or still open.',
    icon: 'checklist',
    accent: 'from-amber-400/22 to-amber-300/0',
    tags: ['GEs', 'Major', 'Transfer'],
  },
  {
    viewId: 'resources',
    title: 'Resource Hub',
    description: 'FAQ answers, official UCSB bookmarks, and short policy snippets with source links.',
    icon: 'resources',
    accent: 'from-gold/22 to-gold/0',
    tags: ['FAQ', 'Links', 'Policies'],
  },
  {
    viewId: 'chat',
    title: 'Campus Q&A',
    description: 'Ask planning questions and get answers with links to catalog, GOLD, and advising pages.',
    icon: 'chat',
    accent: 'from-indigo-400/22 to-indigo-300/0',
    tags: ['Prereqs', 'Registration', 'Advising'],
  },
  {
    viewId: 'dates',
    title: 'Dates & Links',
    description: 'Winter deadlines, pass times, and quick official bookmarks.',
    icon: 'calendar',
    accent: 'from-emerald-400/22 to-emerald-300/0',
    tags: ['Deadlines', 'GOLD', 'Links'],
  },
  {
    viewId: 'flowchart',
    title: 'Economics prep flowchart',
    description: 'Interactive prerequisite map for the demo Economics pathway—tap courses as you complete them.',
    icon: 'flowchart',
    accent: 'from-violet-500/22 to-violet-400/0',
    tags: ['Prereqs', 'ECON sequence'],
  },
]

export const upcomingDeadlines = [
  {
    date: 'Jan 8',
    title: 'Winter pass time — Priority 2',
    description: 'Your assigned registration window opens. Plan in SILVER, then add courses in Gaucho GOLD.',
    priority: 'urgent',
  },
  {
    date: 'Jan 16',
    title: 'Last day to add Winter 2026 classes',
    description: 'Use GOLD to add courses or adjust grading options before the registrar deadline.',
    priority: 'urgent',
  },
  {
    date: 'Feb 13',
    title: 'Department and L&S declaration prep deadlines',
    description: 'Confirm Economics and L&S paperwork deadlines with your department and L&S General Advising.',
    priority: 'upcoming',
  },
  {
    date: 'Mar 6',
    title: 'Quarter withdrawal deadline',
    description: 'Final day to withdraw from Winter 2026 without a late petition.',
    priority: 'normal',
  },
]

export const plannerLegend = {
  major: {
    label: 'Major requirement',
    badgeClass: 'border-sky-400/30 bg-sky-500/15 text-sky-100',
    pillClass: 'bg-sky-400/20 text-sky-100',
  },
  ge: {
    label: 'GE area',
    badgeClass: 'border-amber-400/30 bg-amber-400/15 text-amber-100',
    pillClass: 'bg-amber-400/20 text-amber-100',
  },
  elective: {
    label: 'Elective',
    badgeClass: 'border-emerald-400/30 bg-emerald-400/15 text-emerald-100',
    pillClass: 'bg-emerald-400/20 text-emerald-100',
  },
}

export const plannerTemplate = [
  {
    year: 'Year 1',
    quarters: {
      Fall: [
        { code: 'ECON 1', title: 'Principles of Microeconomics', units: 4, type: 'major' },
        { code: 'MATH 3A', title: 'Calculus with Applications I', units: 4, type: 'major' },
        { code: 'WRIT 2', title: 'Academic Writing', units: 4, type: 'ge' },
      ],
      Winter: [
        { code: 'ECON 2', title: 'Principles of Macroeconomics', units: 4, type: 'major' },
        { code: 'MATH 3B', title: 'Calculus with Applications II', units: 4, type: 'major' },
        { code: 'GE B', title: 'Foreign Language', units: 4, type: 'ge' },
      ],
      Spring: [
        { code: 'ECON 10A', title: 'Intermediate Microeconomic Theory', units: 4, type: 'major' },
        { code: 'ECON 5', title: 'Data and Statistics', units: 4, type: 'major' },
        { code: 'GE C', title: 'Science, Mathematics, and Technology', units: 4, type: 'ge' },
      ],
    },
  },
  {
    year: 'Year 2',
    quarters: {
      Fall: [
        { code: 'ECON 101', title: 'Statistics for Economists', units: 4, type: 'major' },
        { code: 'GE D', title: 'Social Science', units: 4, type: 'ge' },
        { code: 'GE F', title: 'Arts', units: 4, type: 'ge' },
      ],
      Winter: [
        { code: 'ECON 100B', title: 'Intermediate Macroeconomic Theory', units: 4, type: 'major' },
        { code: 'ECON 134A', title: 'Intermediate Financial Economics I', units: 4, type: 'major' },
        { code: 'GE E', title: 'Culture and Thought', units: 4, type: 'ge' },
      ],
      Spring: [
        { code: 'ECON 140A', title: 'Intermediate Microeconomic Theory II', units: 4, type: 'major' },
        { code: 'ECON 115', title: 'International Macroeconomics', units: 4, type: 'major' },
        { code: 'GE G', title: 'Literature', units: 4, type: 'ge' },
      ],
    },
  },
  {
    year: 'Year 3',
    quarters: {
      Fall: [
        { code: 'ECON 171', title: 'Econometrics', units: 4, type: 'major' },
        { code: 'ECON 140B', title: 'Intermediate Microeconomic Theory III', units: 4, type: 'major' },
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
      Winter: [
        { code: 'ECON 134B', title: 'Intermediate Financial Economics II', units: 4, type: 'major' },
        { code: 'ECON 127', title: 'Economics of the Environment', units: 4, type: 'major' },
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
      Spring: [
        { code: 'ECON 130', title: 'Public Policy', units: 4, type: 'major' },
        { code: 'GE NWC', title: 'World Cultures', units: 4, type: 'ge' },
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
    },
  },
  {
    year: 'Year 4',
    quarters: {
      Fall: [
        { code: 'ECON 199', title: 'Independent Studies in Economics', units: 4, type: 'major' },
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
      Winter: [
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
      Spring: [
        { code: 'Free Elective', title: 'Open Elective', units: 4, type: 'elective' },
      ],
    },
  },
]

export const plannerSuggestions = [
  {
    code: 'ECON 101',
    title: 'Statistics for Economists',
    units: 4,
    type: 'major',
    note: 'Upper-division core (Area B on the 2025–26 sheet). Typical after ECON 10A, ECON 5, and MATH 3B.',
    offeredQuarters: ['Winter', 'Fall'],
    offeredNote: 'Usually Winter & Fall',
    reasonTags: ['UD core', 'Prereqs met', 'Major sequence'],
  },
  {
    code: 'ECON 100B',
    title: 'Intermediate Macroeconomic Theory',
    units: 4,
    type: 'major',
    note: 'Upper-division core (Area A). Plan after ECON 2 and ECON 10A are complete.',
    offeredQuarters: ['Winter', 'Spring'],
    offeredNote: 'Check GOLD for your term',
    reasonTags: ['UD core', 'Pre-major complete'],
  },
  {
    code: 'ECON 140A',
    title: 'Intermediate Microeconomic Theory II',
    units: 4,
    type: 'major',
    note: 'Upper-division core (Area C). Often follows ECON 101 in the sample path.',
    offeredQuarters: ['Spring'],
    offeredNote: 'Spring offering — plan ahead',
    reasonTags: ['UD core', 'Major requirement'],
  },
  {
    code: 'ECON 134A',
    title: 'Intermediate Financial Economics I',
    units: 4,
    type: 'major',
    note: 'Counts toward the six Area D electives on the 2025–26 sheet — not a separate core requirement.',
    offeredQuarters: ['Winter'],
    offeredNote: 'Winter offering in demo schedule',
    reasonTags: ['UD elective', 'Area D'],
  },
  {
    code: 'GE E',
    title: 'Culture and Thought',
    units: 4,
    type: 'ge',
    note: 'Completes another GE area while keeping unit load near 12 to 14.',
    offeredQuarters: ['Winter', 'Spring', 'Fall'],
    offeredNote: 'Multiple quarters',
    reasonTags: ['GE progress', 'Balances unit load'],
  },
  {
    code: 'ENGL 10',
    title: 'Introduction to Literary Study',
    units: 4,
    type: 'elective',
    note: 'Breadth elective option if you want reading and writing outside economics this quarter.',
    offeredQuarters: ['Winter'],
    offeredNote: 'Winter elective option',
    reasonTags: ['Breadth elective', 'Writing intensive option'],
  },
]

export const advisorSuggestedCourses = [
  {
    code: 'ECON 100B',
    title: 'Intermediate Macroeconomic Theory',
    type: 'major',
    note: 'Required upper-division core on the 2025–26 Economics B.A. sheet (Area A).',
  },
  {
    code: 'ECON 101',
    title: 'Statistics for Economists',
    type: 'major',
    note: 'Required upper-division core (Area B). Confirm prerequisites in GOLD before enrolling.',
  },
  {
    code: 'ECON 140A',
    title: 'Intermediate Microeconomic Theory II',
    type: 'major',
    note: 'Required upper-division core (Area C).',
  },
  {
    code: 'ECON 134A',
    title: 'Intermediate Financial Economics I',
    type: 'major',
    note: 'Example Area D elective — swap for any approved UD economics elective on your sheet.',
  },
  {
    code: 'GE E',
    title: 'Culture and Thought',
    type: 'ge',
    note: 'Keeps GE progress moving alongside heavier theory courses.',
  },
]

export const requirementSections = [
  {
    id: 'ge',
    title: 'General Education — Areas A–G',
    description:
      'L&S breadth areas for B.A. candidates. Course counts follow the catalog (for example, three courses in Area C).',
    items: [
      {
        id: 'req-a',
        label: 'Area A: English Reading and Composition',
        detail: 'WRIT 2 satisfies Area A in this demo — confirm on your GOLD audit',
        completed: true,
        transferEligible: true,
        courseCodes: ['WRIT 2'],
      },
      {
        id: 'req-b',
        label: 'Area B: Foreign Language',
        detail: 'Three-course sequence not started in this demo path',
        completed: false,
        transferEligible: true,
        courseCodes: ['GE B'],
      },
      {
        id: 'req-c',
        label: 'Area C: Science, Mathematics, and Technology',
        detail: '1 of 3 courses complete in demo (MATH 3A–3B may count — verify in GOLD)',
        completed: false,
        transferEligible: false,
        courseCodes: ['GE C'],
      },
      {
        id: 'req-d',
        label: 'Area D: Social Science',
        detail: '1 of 3 courses planned',
        completed: false,
        transferEligible: false,
        courseCodes: ['GE D'],
      },
      {
        id: 'req-e',
        label: 'Area E: Culture and Thought',
        detail: '1 of 3 courses planned for Year 2 Winter',
        completed: false,
        transferEligible: true,
        courseCodes: ['GE E'],
      },
      {
        id: 'req-f',
        label: 'Area F: Arts',
        detail: '1 of 2 courses planned',
        completed: false,
        transferEligible: false,
        courseCodes: ['GE F'],
      },
      {
        id: 'req-g',
        label: 'Area G: Literature',
        detail: '1 of 2 courses planned',
        completed: false,
        transferEligible: false,
        courseCodes: ['GE G'],
      },
    ],
  },
  {
    id: 'ge-special',
    title: 'Special subject area requirements',
    description: 'Campus-wide requirements in addition to Areas A–G.',
    items: [
      {
        id: 'req-writing',
        label: 'Writing Requirement',
        detail: 'Six courses required — demo shows WRIT 2 plus additional writing in progress',
        completed: false,
        transferEligible: true,
        courseCodes: ['GE WR'],
      },
      {
        id: 'req-euro',
        label: 'European Traditions Requirement',
        detail: 'Satisfied in demo with an approved European traditions course',
        completed: true,
        transferEligible: false,
        courseCodes: ['GE EURO'],
      },
      {
        id: 'req-nwc',
        label: 'World Cultures Requirement',
        detail: 'Planned for Year 3 Spring in this demo roadmap',
        completed: false,
        transferEligible: true,
        courseCodes: ['GE NWC'],
      },
      {
        id: 'req-quant',
        label: 'Quantitative Relationships Requirement',
        detail: 'Often met through major math and economics statistics — verify on your audit',
        completed: true,
        transferEligible: false,
        courseCodes: ['GE QUANT'],
      },
      {
        id: 'req-eth',
        label: 'Ethnicity Requirement',
        detail: 'Approved courses carry Ethnicity credit in GOLD',
        completed: false,
        transferEligible: true,
        courseCodes: ['GE ETH'],
      },
    ],
  },
  {
    id: 'major',
    title: 'Economics B.A. — 2025–26 sheet',
    description:
      'Admission: ECON 1, 2, and 10A with 2.85 GPA (C minimum; ECON 5 and 10A at UCSB). Prep: ECON 5 or PSTAT 120A plus MATH 2A–B, 3A–B, or 34A–B. Upper division: 40 units — 100B, 101, 140A, seven UD electives. Max 4 units of ECON 199; ECON 199RA does not count.',
    items: [
      {
        id: 'req-premajor-gpa',
        label: 'Pre-major admission GPA',
        detail: 'ECON 1, 2, and 10A at UCSB: 2.85 GPA minimum; no grade below C (2025–26 sheet)',
        completed: false,
        transferEligible: false,
        courseCodes: [],
      },
      {
        id: 'req-econ1',
        label: 'ECON 1',
        detail: 'Pre-major — Principles of Microeconomics (10 units with ECON 2)',
        completed: true,
        transferEligible: true,
        courseCodes: ['ECON 1'],
      },
      {
        id: 'req-econ2',
        label: 'ECON 2',
        detail: 'Pre-major — Principles of Macroeconomics',
        completed: true,
        transferEligible: true,
        courseCodes: ['ECON 2'],
      },
      {
        id: 'req-econ10a',
        label: 'ECON 10A',
        detail: 'Pre-major — must be taken at UCSB (5 units)',
        completed: true,
        transferEligible: false,
        courseCodes: ['ECON 10A'],
      },
      {
        id: 'req-econ5',
        label: 'ECON 5 (or PSTAT 120A)',
        detail: 'Preparation for the major — must be taken at UCSB if using ECON 5; grade C or higher',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 5'],
      },
      {
        id: 'req-math3a',
        label: 'MATH 3A',
        detail: 'Preparation for the major — demo path (2A–B or 34A–B also satisfy the sheet)',
        completed: true,
        transferEligible: true,
        courseCodes: ['MATH 3A'],
      },
      {
        id: 'req-math3b',
        label: 'MATH 3B',
        detail: 'Preparation for the major — grade C or higher',
        completed: true,
        transferEligible: false,
        courseCodes: ['MATH 3B'],
      },
      {
        id: 'req-econ100b',
        label: 'ECON 100B',
        detail: 'Upper-division core — Area A (4 units)',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 100B'],
      },
      {
        id: 'req-econ101',
        label: 'ECON 101',
        detail: 'Upper-division core — Area B (4 units)',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 101'],
      },
      {
        id: 'req-econ140a',
        label: 'ECON 140A',
        detail: 'Upper-division core — Area C (4 units)',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 140A'],
      },
      {
        id: 'req-ud-electives',
        label: 'Upper-division electives (7 courses, 28 units)',
        detail:
          'Six from Area D plus one additional (Area D or ECON 118, 136A–C, 137A–B, 138A–B, 185). Demo plan: 115, 134A–B, 171, 140B, 127, 130.',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 115', 'ECON 134A', 'ECON 134B', 'ECON 171', 'ECON 140B', 'ECON 127', 'ECON 130'],
      },
      {
        id: 'req-econ199',
        label: 'ECON 199 (optional)',
        detail: 'Maximum 4 units apply toward the UD major; ECON 199RA does not count (2025–26 sheet)',
        completed: false,
        transferEligible: false,
        courseCodes: ['ECON 199'],
      },
    ],
  },
  {
    id: 'support',
    title: 'Degree units & open electives',
    description: 'Non-major unit space toward 180 total units (L&S B.A.).',
    items: [
      {
        id: 'req-free1',
        label: 'Open elective blocks',
        detail: 'Flexible units beyond the Economics major and GE plan in this demo',
        completed: false,
        transferEligible: true,
        courseCodes: ['Free Elective'],
      },
    ],
  },
]

export const chatbotSeedMessages = [
  {
    id: 'bot-intro',
    sender: 'bot',
    text: 'Hi Maya. I answer broad, high-level questions about UCSB and L&S planning using links to official sources. Anything about your specific transcript, exceptions, petitions, or degree progress should go to L&S General Academic Advising or your department.',
    resources: [
      { label: 'L&S General Academic Advising (source)', url: 'https://uged.ucsb.edu/advising' },
    ],
  },
  {
    id: 'user-question',
    sender: 'user',
    text: 'What classes should I think about for next quarter?',
  },
  {
    id: 'bot-answer',
    sender: 'bot',
    text: 'Based on the 2025–26 Economics B.A. sample path, after ECON 10A and ECON 5 many students take ECON 101, then ECON 100B and ECON 140A as upper-division core courses, while filling Area D electives over junior and senior year. Your real schedule depends on prerequisites and declaration timing—confirm every course in GOLD and with L&S or Economics advising.',
    bullets: [
      'Use the General Catalog and GOLD class search to verify prerequisites and major requirements before you enroll.',
      'If you are considering a double major, minor, or substitution, treat that as advisor-level planning rather than something to finalize from chat alone.',
    ],
    resources: [
      { label: 'L&S General Academic Advising (source)', url: 'https://uged.ucsb.edu/advising' },
      { label: 'UCSB General Catalog (source)', url: 'https://catalog.ucsb.edu/' },
      { label: 'GOLD class search and schedule (source)', url: 'https://my.sa.ucsb.edu/gold/' },
    ],
  },
]

export const winterDates = [
  {
    date: '2026-01-02',
    month: 'Jan',
    day: '02',
    title: 'Aid and charges post to BARC',
    detail: 'Typical timing for Winter aid to appear against tuition and fees before instruction begins.',
    category: 'billing',
  },
  {
    date: '2026-01-05',
    month: 'Jan',
    day: '05',
    title: 'Winter 2026 instruction begins',
    detail: 'Classes start for the Winter quarter.',
    category: 'academic',
  },
  {
    date: '2026-01-08',
    month: 'Jan',
    day: '08',
    title: 'Winter pass time — Priority 2',
    detail:
      'Registration window for your assigned pass time. Finalize your planned schedule here, then add courses in Gaucho GOLD when your window opens.',
    category: 'registration',
    priority: 'urgent',
  },
  {
    date: '2026-01-12',
    month: 'Jan',
    day: '12',
    title: 'L&S and department advising for spring planning',
    detail: 'Many L&S students meet General Advising or their department about spring enrollment and major paperwork.',
    category: 'major',
  },
  {
    date: '2026-01-16',
    month: 'Jan',
    day: '16',
    title: 'Add deadline',
    detail: 'Last day to add classes in GOLD without a late petition.',
    category: 'academic',
  },
  {
    date: '2026-02-02',
    month: 'Feb',
    day: '02',
    title: 'Drop deadline',
    detail: 'Last day to drop most classes without a petition.',
    category: 'academic',
  },
  {
    date: '2026-02-10',
    month: 'Feb',
    day: '10',
    title: 'Spring pass time — Priority 2',
    detail: 'Next-quarter enrollment by pass time. Check holds, prerequisites, and unit load before GOLD opens for your window.',
    category: 'registration',
    priority: 'upcoming',
  },
  {
    date: '2026-02-13',
    month: 'Feb',
    day: '13',
    title: 'Department and L&S declaration deadlines',
    detail: 'Confirm Economics and L&S paperwork deadlines with your department and L&S General Advising.',
    category: 'major',
  },
  {
    date: '2026-03-06',
    month: 'Mar',
    day: '06',
    title: 'Withdrawal deadline',
    detail: 'Final day to withdraw from the quarter before finals week.',
    category: 'academic',
  },
  {
    date: '2026-03-14',
    month: 'Mar',
    day: '14',
    title: 'Winter finals begin',
    detail: 'Final exam period begins and runs through March 20.',
    category: 'academic',
  },
]

/**
 * Flowchart for the 2025–26 Economics B.A. prep path (nodes + edges).
 * `kind: 'gate'` nodes are visual joins; only `course` nodes are tappable.
 * Center-column courses use `column: 'center'` for lighter-blue styling.
 */
export const econPrepFlowchart = {
  width: 1320,
  height: 620,
  zones: [
    {
      id: 'admission',
      track: 'admission',
      step: 'Step 1',
      label: 'Pre-major admission',
      sublabel: 'Not the major yet — qualify to declare (ECON 1, 2, 10A · 2.85 GPA)',
      x: 12,
      y: 12,
      w: 628,
      h: 198,
    },
    {
      id: 'prep',
      track: 'prep',
      step: 'Step 2',
      label: 'Preparation for the major',
      sublabel: 'Still before UD major units — ECON 5 or PSTAT 120A + calculus',
      x: 12,
      y: 218,
      w: 628,
      h: 370,
    },
    {
      id: 'major',
      track: 'major',
      step: 'Step 3',
      label: 'The Economics major',
      sublabel: 'Upper-division coursework · 40 units after declaration',
      x: 652,
      y: 12,
      w: 656,
      h: 576,
    },
  ],
  edges: [
    { from: 'econ1', to: 'econ2', fromSide: 'bottom', toSide: 'top', stroke: '#38bdf8' },
    { from: 'math3a', to: 'math3b', fromSide: 'bottom', toSide: 'top', stroke: '#60a5fa' },
    { from: 'econ1', to: 'gate10a', fromSide: 'right', toSide: 'left', stroke: '#fbbf24' },
    { from: 'econ2', to: 'gate10a', fromSide: 'right', toSide: 'left', stroke: '#38bdf8' },
    { from: 'math3a', to: 'gate10a', fromSide: 'right', toSide: 'left', stroke: '#a855f7' },
    { from: 'gate10a', to: 'econ10a', fromSide: 'right', toSide: 'left', stroke: '#2dd4bf' },
    { from: 'econ10a', to: 'gate101', fromSide: 'right', toSide: 'left', stroke: '#fcd34d' },
    { from: 'math3b', to: 'gate101', fromSide: 'right', toSide: 'left', stroke: '#818cf8' },
    { from: 'gate101', to: 'econ101', fromSide: 'right', toSide: 'left', stroke: '#f97316' },
    { from: 'econ1', to: 'gate5', fromSide: 'right', toSide: 'left', stroke: '#fb7185' },
    { from: 'math3a', to: 'gate5', fromSide: 'right', toSide: 'left', stroke: '#c084fc' },
    { from: 'gate5', to: 'econ5', fromSide: 'right', toSide: 'left', stroke: '#4ade80' },
    { from: 'math3a', to: 'gatePstat', fromSide: 'right', toSide: 'left', stroke: '#c084fc' },
    { from: 'gatePstat', to: 'pstat120a', fromSide: 'right', toSide: 'left', stroke: '#a78bfa' },
    { from: 'econ2', to: 'gate100b', fromSide: 'right', toSide: 'left', stroke: '#22d3ee' },
    { from: 'econ10a', to: 'gate100b', fromSide: 'right', toSide: 'left', stroke: '#14b8a6' },
    { from: 'gate100b', to: 'econ100b', fromSide: 'right', toSide: 'left', stroke: '#22d3ee' },
    { from: 'econ10a', to: 'gate140a', fromSide: 'right', toSide: 'left', stroke: '#14b8a6' },
    { from: 'econ101', to: 'gate140a', fromSide: 'right', toSide: 'left', stroke: '#fde047' },
    { from: 'gate140a', to: 'econ140a', fromSide: 'right', toSide: 'left', stroke: '#f97316' },
    { from: 'econ100b', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#facc15' },
    { from: 'econ140a', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#facc15' },
    { from: 'econ101', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#fde047' },
    { from: 'econ10a', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#2dd4bf' },
    { from: 'econ2', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#38bdf8' },
    { from: 'math3b', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#818cf8' },
    { from: 'econ5', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#4ade80' },
    { from: 'pstat120a', to: 'gateUd', fromSide: 'right', toSide: 'left', stroke: '#a78bfa' },
    { from: 'gateUd', to: 'udElectives', fromSide: 'right', toSide: 'left', stroke: '#facc15' },
    { from: 'econ101', to: 'econ199', fromSide: 'right', toSide: 'left', stroke: '#94a3b8' },
  ],
  nodes: [
    {
      id: 'econ1',
      kind: 'course',
      track: 'admission',
      phase: 'premajor',
      column: 'prep',
      label: 'ECON 1',
      subtitle: 'Pre-major (2.85 GPA)',
      x: 32,
      y: 88,
      w: 192,
      h: 80,
      requires: [],
    },
    {
      id: 'econ2',
      kind: 'course',
      track: 'admission',
      phase: 'premajor',
      column: 'prep',
      label: 'ECON 2',
      subtitle: 'Pre-major',
      x: 248,
      y: 88,
      w: 192,
      h: 80,
      requires: ['econ1'],
    },
    {
      id: 'math3a',
      kind: 'course',
      track: 'prep',
      phase: 'premajor',
      column: 'prep',
      label: 'MATH 3A',
      subtitle: 'Prep for major',
      x: 32,
      y: 278,
      w: 192,
      h: 80,
      requires: [],
    },
    {
      id: 'math3b',
      kind: 'course',
      track: 'prep',
      phase: 'premajor',
      column: 'prep',
      label: 'MATH 3B',
      subtitle: 'Prep for major',
      x: 32,
      y: 394,
      w: 192,
      h: 80,
      requires: ['math3a'],
    },
    {
      id: 'gate10a',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 268,
      y: 100,
      w: 77,
      h: 58,
    },
    {
      id: 'gate101',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 268,
      y: 318,
      w: 77,
      h: 58,
    },
    {
      id: 'gate5',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 268,
      y: 358,
      w: 77,
      h: 58,
    },
    {
      id: 'gatePstat',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 268,
      y: 478,
      w: 77,
      h: 58,
    },
    {
      id: 'econ10a',
      kind: 'course',
      track: 'admission',
      phase: 'premajor',
      column: 'center',
      label: 'ECON 10A',
      subtitle: 'Pre-major · at UCSB',
      x: 400,
      y: 80,
      w: 220,
      h: 92,
      requires: ['econ1', 'econ2', 'math3a'],
    },
    {
      id: 'econ5',
      kind: 'course',
      track: 'prep',
      phase: 'premajor',
      column: 'center',
      label: 'ECON 5',
      subtitle: 'Prep · at UCSB',
      x: 400,
      y: 338,
      w: 220,
      h: 92,
      requires: ['econ1', 'math3a'],
    },
    {
      id: 'pstat120a',
      kind: 'course',
      track: 'prep',
      phase: 'premajor',
      column: 'center',
      label: 'PSTAT 120A',
      subtitle: 'Prep · or ECON 5',
      x: 400,
      y: 458,
      w: 220,
      h: 92,
      requires: ['math3a'],
    },
    {
      id: 'gate100b',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 668,
      y: 52,
      w: 77,
      h: 58,
    },
    {
      id: 'gate140a',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 668,
      y: 152,
      w: 77,
      h: 58,
    },
    {
      id: 'econ100b',
      kind: 'course',
      track: 'major',
      phase: 'upper',
      column: 'upper',
      label: 'ECON 100B',
      subtitle: 'UD core (Area A)',
      x: 720,
      y: 36,
      w: 200,
      h: 88,
      requires: ['econ2', 'econ10a'],
    },
    {
      id: 'econ140a',
      kind: 'course',
      track: 'major',
      phase: 'upper',
      column: 'upper',
      label: 'ECON 140A',
      subtitle: 'UD core (Area C)',
      x: 720,
      y: 136,
      w: 200,
      h: 88,
      requires: ['econ10a', 'econ101'],
    },
    {
      id: 'econ101',
      kind: 'course',
      track: 'major',
      phase: 'upper',
      column: 'upper',
      label: 'ECON 101',
      subtitle: 'UD core (Area B)',
      x: 720,
      y: 236,
      w: 200,
      h: 88,
      requires: ['econ10a', 'math3b'],
    },
    {
      id: 'gateUd',
      kind: 'gate',
      gateKind: 'all',
      label: 'All',
      x: 668,
      y: 352,
      w: 77,
      h: 58,
    },
    {
      id: 'udElectives',
      kind: 'course',
      track: 'major',
      phase: 'upper',
      column: 'upper',
      label: 'UD electives',
      subtitle: '7 courses · Area D + 1',
      x: 1000,
      y: 100,
      w: 280,
      h: 120,
      requires: ['econ2', 'math3b', 'econ10a', 'econ101', 'econ100b', 'econ140a'],
      requiresAny: ['econ5', 'pstat120a'],
    },
    {
      id: 'econ199',
      kind: 'course',
      track: 'major',
      phase: 'upper',
      column: 'upper',
      label: 'ECON 199',
      subtitle: 'Optional · max 4 units',
      x: 1000,
      y: 260,
      w: 280,
      h: 88,
      requires: ['econ101'],
    },
  ],
}

/** Course nodes only (used for completion / prerequisite logic). */
export const econPrepMapNodes = econPrepFlowchart.nodes
  .filter((n) => n.kind === 'course')
  .map(({ id, label, subtitle, requires, requiresAny, column, phase, track }) => ({
    id,
    label,
    subtitle,
    requires,
    requiresAny,
    column,
    phase,
    track,
  }))
